name: GitHub Actions Unit Test

on: [push]

jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - name: Make Unit Test
              uses: actions/checkout@v2
            - run: apt install libgtest-dev
            - run: make unit-test
